# Generated by Django 4.2.7 on 2023-12-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertdatabase',
            name='field',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='insert_img/'),
        ),
    ]
