# Generated by Django 4.2.7 on 2023-12-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Operations', '0003_image_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('topic', models.TextField()),
                ('describe', models.TextField()),
                ('field', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
